### ISSUE TITLE
The documentation for `run` and `use` is wrong

### ISSUE THREAD

**Issue by loreanvictor** [loreanvictor/tmplr#13]
`run` and `use` commands accept objects as arguments for `with` and `read` parameters, but in the documents they are written as strings. this is what the docs suggest:

```yml
run: some-recipe.yml
with:
  - x
  - y:
      path: './{{some-thing}}/whatever'
read:
  - z
```

while the correct format is:
```yml
run: some-recipe.yml
with:
  x: x
  y:
    path: './{{some-thing}}/whatever'
read:
  z: z
```
