### ISSUE TITLE
Issues with glob copying

### ISSUE THREAD

**Issue by tommy-mitchell** [loreanvictor/tmplr#14]
I recently tried updating a template to support copying/deleting via glob patterns (https://github.com/tommy-mitchell/cli-template), but some files are seemingly being ignored. I'm using these commands:

```yml
# setup project

- copy: ./template/**/*.*
  to: ./

# finish

- remove: ./template/**/*.*
- remove: .tmplr.yml
```

However, these files are not being copied or removed:

```
\__ template/
    \__ .github/
        \__ workflows/
            \__ main.yml
    \__ test/
        \__ fixtures/
            \__ .gitkeep
    \__ .gitignore
    \__ .xo-config.json
```

It looks like files/folders starting with a period are being ignored.

**Comment by loreanvictor** [comment]
That is by design (as per [minimatch](https://github.com/isaacs/minimatch#dot)), to avoid accidentally copying files and folders that should not be copied (or updated, or removed, etc.). If you need to copy / update / remove those files / folders, you need to specify the dot explicitly ([sandbox](https://codesandbox.io/p/sandbox/tmplr-copy-star-hidden-files-lt86m3?file=%2F.tmplr.yml%3A1%2C1-12%2C15)):

```yml
steps:
  - copy: ./template/**/*
    to: ./dest
    
  - copy: ./template/**/.**/**/*
    to: ./dest
    
  - copy: ./template/**/.*
    to: ./dest

  - copy: ./template/**/.**/**/.*
    to: ./dest
```

I suppose I could add a `hidden` argument to copy / update / remove commands to also include hidden files and folders, though this would be a bit of an unsafe option.

**Comment by tommy-mitchell** [comment]
Ah, I didn’t realize. I’ll try out those commands tomorrow. Thanks :)

[Here’s](https://github.com/mrmlnc/fast-glob#dot) how `fast-glob` and `globby` handle dot files.

**Comment by tommy-mitchell** [comment]
That worked perfectly for copying everything, but I'm having trouble removing the empty folders now. For example, with your sandbox:

```yml
steps:
  - copy: ./template/**/*
    to: ./dest

  - copy: ./template/**/.**/**/*
    to: ./dest

  - copy: ./template/**/.*
    to: ./dest

  - copy: ./template/**/.**/**/.*
    to: ./dest

  - remove: ./dest/**/*
  - remove: ./dest/**/.**/**/*
  - remove: ./dest/**/.*
  - remove: ./dest/**/.**/**/.*
```

This leaves:

```
\__ dest/
    \__ .hidden/
    \__ stuff/
```

<details>
<summary>Command output</summary>

```
❯ npx tmplr
✔ Copied: template/doc.md -> dest/doc.md
✔ Copied: template/stuff/code.js -> dest/stuff/code.js
✔ Copied: template/.hidden/other-code.js -> dest/.hidden/other-code.js
✔ Copied: template/.stuff -> dest/.stuff
✔ Copied: template/.hidden/.other-file -> dest/.hidden/.other-file
✔ Removed: dest/doc.md
✔ Removed: dest/stuff/code.js
✔ Removed: dest/.hidden/other-code.js
✔ Removed: dest/.stuff
✔ Removed: dest/.hidden/.other-file
```

</details>
