### ISSUE TITLE
Add `append` and `prepend` commands

### ISSUE THREAD

**Issue by loreanvictor** [loreanvictor/tmplr#20]
These are useful for reusable recipes, as they might need to add to some files (for example, the README) without wholesale changing them. They should read some file, replace all variables in it, and append/prepend the content to some other file (without updating their variables).

```yml
prepend: header.md
to: README.md
```

Should it also support glob pattern? I am unsure, lets not do it for the first iteration at least.

**Comment by loreanvictor** [comment]
considering #4 , perhaps it is useful to have the input value be an expression instead of a file path:

```yml
prepend: "# Hallo!"
to: README.md
```

and have the combination of these two features handle appending / prepending files:

```yml
prepend:
  from file: header.md
to: README.md
```

**Comment by loreanvictor** [comment]
I'm unsure about this, but it might be a nice feature to be able to append / prepend and write (using a `write` command) to specific positions in a JSON / YAML file too:

```yaml
# add an eslint rule

append: '"@typescript-eslint/no-var-requires": "off"'
to: .eslintrc.json
path: /rules
```
```yaml
# add a step before the 3rd step
# to GH action workflow

prepend: |
      - name: Check code styling
        run: npm run eslint
to: .github/workflows/publish.yml
path: jobs/do/steps/3
```
```yaml
# add a bunch of dependencies to project.
# uses a new `write` command.

steps:
  - write: '^6.1.0'
    to: package.json
    path: /devDependencies/@typescript-eslint~1eslint-plugin

  - write: '^6.1.0'
    to: package.json
    path: /devDependencies/@typescript-eslint~1parser
```

here, I've used [JSON Pointer](https://datatracker.ietf.org/doc/html/rfc6901) format for addresses. I suspect JSON and YAML files can be updated in specific addresses, without the overall formatting of the file being touched, using [`json-source-map`](https://www.npmjs.com/package/json-source-map) and [`mapped-yaml`](https://www.npmjs.com/package/mapped-yaml).

## Pros

- reusable recipes can do more granular stuff
- granular config modification, for example selecting which features are to be turned on,
  and adding them to project config accordingly.

## Cons

- requires some work to ensure recipe-generated config sits nice alongside manually written config.
- generally mixing human written and autogenerated code can be problematic.

overall, I'd say the idea is enticing but requires further thought.
