### ISSUE TITLE
Add a `write` command

### ISSUE THREAD

**Issue by loreanvictor** [loreanvictor/tmplr#23]
The command would simply write to a file. This can be useful for creating files without source templates, however the main idea is to allow the command to write to specific parts of a file, if they are for example `json` or `yaml` files.

```yaml
# create a file
write: some stuff
to: myfile.txt
```
```yaml
# add a dependency
write: '^6.1.0'
to: package.json
at: 'devDependencies/@typescript-eslint~1eslint-plugin'
```
```yaml
# add a workflow step
write: |
      - name: check code style
        run: npm run lint
to: .github/workflows/publish.yml
after: jobs/run/steps/4
```

[JSON Pointer](https://datatracker.ietf.org/doc/html/rfc6901) format is used here. I suspect [json-source-map](https://www.npmjs.com/package/json-source-map) and [mapped-yaml](https://www.npmjs.com/package/mapped-yaml) (or equivalent libraries) can be used to precisely alter some JSON or YAML file while maintaining its formatting as much as possible.

**Comment by loreanvictor** [comment]
This command could also benefit [from the proposed filtering of files](#24) if it were to support glob patterns, specifically to allow the content to also be evaluated per file. This could basically remove the need for [the proposed `append` and `prepend` commands](#20).

```yaml
write: '{{ license }}\n{{ content }}'
to: **/*.(jsx?|tsx?|cpp|java)
where:
  steps:
    - read: content
      from file: __file__
  eval: '{{ content | not matches: /.../ }}'
```
