### ISSUE TITLE
Add filtering to commands operating on multiple files.

### ISSUE THREAD

**Issue by loreanvictor** [loreanvictor/tmplr#24]
A stronger filtering system for commands accepting glob patterns as input (`copy`, `update`, `remove`, and [proposed `append` and `prepend`](#20) commands) can be particularly useful, specifically combined with the proposed [`from file`](#4) expression. For example the following would allow adding license headers to all files lacking a license header:

```yaml
prepend:
  from file: license
to: **/*.(jsx?|tsx?|cpp|java)
where:
  steps:
    - read: content
      from file: __file__
  eval: '{{ content | not matches: /^\s*\/\*\*\s*\*\s*\@license/ }}'
```

This would require setting a loop variable `__file__`, which would be the address (absolute?) of the file. Adding some pipes for extracting directory name, filename, path, extensions, etc from file addresses would be nice.
