### ISSUE TITLE
Add support for writing to / reading from specific fields in JSON / YAML files

### ISSUE THREAD

**Issue by loreanvictor** [loreanvictor/tmplr#26]
`write` and `from file` commands can benefit from being able to specific fields in JSON / YAML files, specifically for recipes that want to alter an existing projects. For example, the following could read the name of the package:

```yaml
read: package_name
from file: package.json
at: /name
```

Or the following could add dependencies:

```yaml
write: '^6.0.1'
to: package.json
at: /dependencies/some-package
```

Write can support `at`, `before` and `after` properties to allow inserting to arrays as well. The field addressing syntax is [JSON Pointer](https://www.rfc-editor.org/rfc/rfc6901). It is important to not screw up files that are written to, maintaining their styling, for which packages such as [json-source-map](https://www.npmjs.com/package/json-source-map) and [mapped-yaml](https://www.npmjs.com/package/mapped-yaml) can be used (perhaps a separate package should be written for this specific purpose). Additionally, the filesystem object might want to do some caching of files that are read / written to, to save on processing costs (though this might be a later-on feature).
