### ISSUE TITLE
`update` and `copy` commands don't work on Windows

### ISSUE THREAD

**Issue by fwextensions** [loreanvictor/tmplr#29]
I really want to use this utility, but it doesn't seem to work reliably on Windows.  I've got a super simple test `.tmplr.yml` file that looks like this:

```yaml
steps:
  - read: pluginName
    prompt: What is the name of your plugin?
    default: Bloop Blorp

  - update: derp.txt

  - write: '{{ pluginName | kebab-case }}'
    to: ffs.txt
```
`derp.txt`:
```
{{ tmplr.pluginName | kebab-case }}
```

When I run `npx tmplr preview` in the Windows terminal, it prompts for the `pluginName` var and correctly writes it out to `ffs.txt` in the preview folder.  But `derp.txt` doesn't get updated at all.  I also had a `copy` command that I was trying that similarly had no effect.

If I run the same command inside a WSL shell, the `derp.txt` file is updated as expected.  So this seems like a Windows vs. Linux issue.  Has it been tested on Windows?

**Comment by loreanvictor** [comment]
> Has it been tested on Windows?

Not specifically, the APIs should generally behave in a cross-platform manner, though there is always possibility of some little mistake 😅 Can you try the following recipe?

```yml
steps:
  - read: pluginName
    prompt: What is the name of your plugin?
    default: Bloop Blorp

  - read: derp
    from file: derp.txt

  - write: '{{ derp }}'
    to: derp.txt
```
