### ISSUE TITLE
Is there a way to set variables depending on choices?

### ISSUE THREAD

**Issue by Judahh** [loreanvictor/tmplr#3]
Is there a way to programatically read a var? 
something like:
```yaml
- read: database_type
    prompt: What database type do you want to use?
    choices:
      - MongoDB
      - PGSQL
      - MSSQL

  - if: database_type == 'MongoDB'
    read: database_var
    eval: "const database = new MongoPersistence(readDatabase, {\n\tsample: new SampleSchema(),\n});"
    else:
      read: database_var
      eval: "const database = new DAOPersistence(sql, {\n\tsample: new SampleDAO(),\n});"

  - if: database_type == 'PGSQL'
    steps:
      - read: database_import
        eval: "import { PGSQL } from '@flexiblepersistence/pgsql';\nimport SampleDAO from './dAOs/sampleDAO';"
      - read: database_sql
        eval: "const sql = new PGSQL(readDatabase);"
    else:
      if: database_type == 'MSSQL'
      steps:
      - read: database_import
        eval: "import { MSSQL } from '@flexiblepersistence/mssql';\nimport SampleDAO from './dAOs/sampleDAO';"
      - read: database_sql
        eval: "const sql = new MSSQL(readDatabase);"
      else:
        steps:
          - read: database_import
            eval: "import SampleSchema from './schemas/sampleSchema';"
          - read: database_sql
            eval: ""
```

**Comment by loreanvictor** [comment]
Yes, multiple ways. You can do it inline using [eval with steps](https://github.com/loreanvictor/tmplr#eval):

```yml
steps:
  - read: database
    prompt: Which database?
    choices:
      - MongoDB:
          steps:
            - read: var
              eval: 'X'
          eval: 'MongoDB'
      - Postgres:
          steps:
            - read: var2
              eval: 'Y'
          eval: 'Postgres'
  - update: '*.txt'
```

Or you can check _inequality_ by combining [if](https://github.com/loreanvictor/tmplr#if) and [skip](https://github.com/loreanvictor/tmplr#pipes):

```yml
steps:
  - read: database
    prompt: Which database?
    choices:
      - MongoDB
      - Postgres
  - if:
      eval: '{{ database | skip: MongoDB }}' # if database is NOT MongoDB
    read: var2
    eval: 'Y'
    else:
      read: var
      eval: 'X'
  - update: '*.txt'
```

That said, I would recommend NOT doing that unless you plan to also do the corresponding updates / copies alongside the reading/defining conditional variables, as otherwise your files would have variables that are not updated (since they are not defined). For example, if you have `some_file.txt` like this:

```txt
database: {{ tmplr.database }}
var: {{ tmplr.var }}
var2: {{ tmplr.var2 }}
```

and you run any of the templating recipes outlined above and choose `MongoDB`, then `some_file.txt` would become the following:

```txt
database: MongoDB
var: X
var2: {{ tmplr.var2 }}
```

Which is perhaps not the intended behavior. The correct version would be something like this:

```yml
steps:
  - read: database
    prompt: Which database?
    choices:
      - MongoDB
      - Postgres
  - if:
      eval: '{{ database | skip: MongoDB }}' # if database is NOT MongoDB
    steps:
      - read: var2
        eval: 'Y'
      - update: 'some_file.txt'
    else:
      steps:
        - read: var
          eval: 'X'
        # Update different files when different variables are defined.
        - update: 'some_other_file.txt'
```
