### ISSUE TITLE
Enable pipes to be applied to things like `filesystem.rootdir`

### ISSUE THREAD

**Issue by fwextensions** [loreanvictor/tmplr#31]
It would be nice to be able to use a transformed version of the current directory name, something like this:

```yaml
  - read: pluginName
    prompt: What is the name of your plugin?
    default:
      from: {{ filesystem.rootdir | Capital Case }}
```

Tried doing something similar with an eval string, but it didn't work.

**Comment by loreanvictor** [comment]
[You already can](https://stackblitz.com/edit/stackblitz-starters-hoxnm1?file=package.json):

```yaml
steps:
  - read: pluginName
    prompt: What is the name of your plugin?
    default:
      eval: '{{ filesystem.rootdir | Capital Case }}'
```

P.S. its strange, I thought I already commented on this 😅
