### ISSUE TITLE
Temp directories aren't removed if CLI is killed

### ISSUE THREAD

**Issue by fwextensions** [loreanvictor/tmplr#35]
I'm trying to create a package that you can use like `npm create foo` to scaffold a project directory using tmplr.  To do this, there needs to be a `bin` key in the `package.json` that gets run when the `create` command is executed.  I made a really simple node script for the `bin.js`:

```js
#!/usr/bin/env node
const { execSync } = require("child_process");
const { relative } = require("path");
const command = `npx tmplr use local:${relative(process.cwd(), __dirname)}`;
execSync(command, { stdio: "inherit" });
```

I haven't published it yet, so testing locally via something like `npx ..\create-foo`.  Getting the relative path from the current directory to where the `.tmplr.yml` file seemed to be necessary, as I think it was creating the output within the temp directory and then removing it at the end, leaving nothing behind.

Anyway, there's a prompt in the `tmplr` file and if I kill the command at that point, the local `.use-***` temp directory is not cleaned up.  If I run a "normal" recipe with `npx tmplr`, the directory is cleaned up even if I kill the process.

Another thing that happens in this case is that the `exists` command doesn't seem to find a local directory.  So if I run the script from `/projects/test/` and there's a local `foo/` directory, the `if: exists:` below doesn't match when `outputPath` is `foo`, so the prompt isn't shown and the directory is removed:

```yaml
  - if:
      exists: '{{ outputPath }}'
    prompt: '"{{ outputPath }}" already exists. Delete it before continuing?'
    choices:
      - Yes
      - No:
          skip: steps

  - remove: '{{ outputPath }}'
```

I belatedly realized I didn't actually need the `bin.js` file and could just put an npm command in the `bin` field.  But setting that to `npx tmplr use local:.` produces the same bugs as above.

It's possible I'm not setting the paths or using the commands correctly here, but there may also be some bug when the `npx tmplr` command is run from some other package's npm script.

**Comment by loreanvictor** [comment]
ok I'd need to check these issues. the `use-***` folder not getting deleted might be a bug that I'll look into.

on the other issue, can you provide an example of `outputPath`?

**Comment by fwextensions** [comment]
These are the steps before the `if` check above:

```yaml
  - read: pluginName
    prompt: 'Enter the name of the plugin:'
    default:
      eval: '{{ filesystem.scopedir | Capital Case }}'

  - read: outputDir
    prompt: 'Enter the directory in which to create the plugin:'
    default:
      eval: '{{ pluginName | kebab-case }}'

  - read: outputPath
    eval: '../{{ outputDir }}'
```

So if you enter a name like `My Test`, the `outputPath` will be `../my-test`.  The `..` is necessary because the working directory seems to be set to the temp directory.  

The package has been published and can be run as `npm create fwidgets@latest`.  Canceling that when the prompt is shown will leave the temp directory behind.  

The code for the create tool is here: https://github.com/fwextensions/fwidgets/tree/main/packages/create-fwidgets
