### ISSUE TITLE
Problem with `use` and `exists`

### ISSUE THREAD

**Issue by dshimkoski** [loreanvictor/tmplr#38]
```yaml
steps:
  - if:
      exists: '../.npmrc'
    prompt: 'overwrite .npmrc?'
    choices:
      - yes
      - no:
          skip: steps
  - copy: .npmrc
    to: ../.npmrc
```

If we `tmplr use local:/recipes/npmrc` the file is created, but subsequent runs never detect the file.

This is due to `this.exists.filesystem.absolute()` in the `exists` command resolving everything in relation to the root of the recipe rather than the scope.

Any thoughts on how to patch this?

Thank you!

**Comment by dshimkoski** [comment]
As an aside, is it possible to perform multiple file check / overwrite prompts like this in sequence in a single recipe or do I have to break them up into multiple recipes? The docs on the `skip` directive are a bit unclear on the possibilities.

**Comment by loreanvictor** [comment]
Ok this is a bug, and its not isolated to `exists`, generally all commands / expressions supporting glob are (incidentally) affected by this issue. It is also not relevant to absolute / relative paths too, it happens because these commands / expressions produce a list of files first, then filter through them to see which ones match the given pattern, but they list all files in the root directory (which is the local recipe folder) and not the scope directory (the project). For example, [this](https://github.com/loreanvictor/tmplr-core/blob/b813aa3a1efeeddd1797be8c60081145f26a7d62/src/command/copy.ts#L23-L25) is how `copy` command works:

```ts
...
    await Promise.all(
      (await this.copy.filesystem.ls(this.copy.filesystem.root))
        .map(path => this.copy.filesystem.absolute(path))
        .filter(path => matcher.match(path))
        .map(async src => {
...
```

Same for [remove](https://github.com/loreanvictor/tmplr-core/blob/b813aa3a1efeeddd1797be8c60081145f26a7d62/src/command/remove.ts#L19-L23), [update](https://github.com/loreanvictor/tmplr-core/blob/b813aa3a1efeeddd1797be8c60081145f26a7d62/src/command/update.ts#L17-L21), and [exists](https://github.com/loreanvictor/tmplr-core/blob/b813aa3a1efeeddd1797be8c60081145f26a7d62/src/expr/exists.ts#L17-L19).

I suspect the solution is to call `ls()` in scope instead of root. I will check this out later and if it fixes the issue, I'll push an update.

@dshimkoski In the meanwhile, you can use `from file`, which doesn't support a glob pattern and so is immune from this bug. Simply use it in place of `exists`, and since you aren't using a glob pattern, it will work as you intended.

```yml
steps:
  - if:
      from file: '../.npmrc'
    prompt: 'overwrite .npmrc?'
    choices:
      - yes
      - no:
          skip: steps
  - copy: .npmrc
    to: ../.npmrc
```

**Comment by loreanvictor** [comment]
@dshimkoski as for your second question: yes, I would recommend simply not using `skip`:

```yml
steps:
  - if:
      from file: '../.npmrc'
    prompt: 'overwrite .npmrc?'
    choices:
      - yes:
          copy: .npmrc
          to: ../.npmrc
      - no
```
