### ISSUE TITLE
Read values from a file?

### ISSUE THREAD

**Issue by YuriGal** [loreanvictor/tmplr#9]
Is there a way to define a simple text file with key/value pairs for variable name/values and have recipe read values from that file? Or any other simple straightforward way to assign literal values to a variables? The idea is - when a repo is created from the template user just supplies their own literal values and runs the recipe that copies template files using this values for variables.

**Comment by YuriGal** [comment]
I think I found a way, thanks!

**Comment by loreanvictor** [comment]
@YuriGal may I ask how did you manage to achieve this?

**Comment by YuriGal** [comment]
After some trial and error I realized that `tmplr` kind of supports what I need already, and I can simply do something like
```yaml
steps:
   - read: variable_1
     eval: 'value_1'
   - read: variable_2
     eval: 'value_2'
   # ...etc...
   - copy ./templates/fille1.tmplr.js
     to: ./src/file1.js
   - copy ./templates/fille2.tmplr.js
     to: ./src/file2.js
```
